package main

import (
	"context"
	"fmt"
	"io"
	"log"
	"strings"
)

// Job represents the integration flow to be executed.
// In a real system, this would be generated by the AI and sent via Redis.
type Job struct {
	ID          string            `json:"id"`
	Name        string            `json:"name"`
	Source      SourceConfig      `json:"source"`
	Destination DestinationConfig `json:"destination"`
}

type SourceConfig struct {
	Type     string            `json:"type"` // e.g., "REST", "DATABASE"
	URL      string            `json:"url,omitempty"`
	Query    string            `json:"query,omitempty"` // For Database
	ConnStr  string            `json:"conn_str,omitempty"` // For Database
	Auth     map[string]string `json:"auth"`
}

type DestinationConfig struct {
	Type string            `json:"type"` // e.g., "SFTP"
	Host string            `json:"host"`
	User string            `json:"user"`
	Path string            `json:"path"`
	Auth map[string]string `json:"auth"`
}

// Worker executes jobs.
type Worker struct {
	ID string
}

func NewWorker(id string) *Worker {
	return &Worker{ID: id}
}

func (w *Worker) Process(ctx context.Context, job Job) error {
	log.Printf("[%s] Processing job: %s (%s)", w.ID, job.Name, job.ID)

	// 1. Initialize Source Reader
	var reader io.Reader
	var err error

	switch job.Source.Type {
	case "REST":
		// Mock REST data for now
		mockData := "id,name,email\n1,John Doe,john@example.com\n2,Jane Doe,jane@example.com"
		reader = strings.NewReader(mockData)
	case "DATABASE":
		dbSource := NewDBSource(job.Source)
		reader, err = dbSource.StreamQuery()
		if err != nil {
			return fmt.Errorf("failed to query database: %w", err)
		}
	default:
		return fmt.Errorf("unsupported source type: %s", job.Source.Type)
	}

	// 2. Initialize Destination Writer
    if job.Destination.Type == "SFTP" {
        sink := NewSFTPSink(job.Destination)
        if err := sink.WriteFromStream(reader); err != nil {
            return fmt.Errorf("SFTP transfer failed: %w", err)
        }
    } else {
        return fmt.Errorf("unsupported destination type: %s", job.Destination.Type)
    }

	// 3. Stream Data (Handled inside WriteFromStream for now, but ideally separated)
	// _, err = io.Copy(writer, reader)

	log.Printf("[%s] Job completed successfully", w.ID)
	return nil
}

// Mock function to simulate receiving a job
func GetMockJob() Job {
	return Job{
		ID:   "job-123",
		Name: "Sync Leads to SFTP",
		Source: SourceConfig{
			Type: "REST",
			URL:  "https://reqres.in/api/users",
		},
		Destination: DestinationConfig{
			Type: "SFTP",
			Host: "localhost:2222",
			User: "tester",
			Path: "/upload/users.json",
			Auth: map[string]string{"password": "password"},
		},
	}
}
